# Generated by Django 5.2.4 on 2025-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_list',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car_list',
            name='price',
        ),
        migrations.AddField(
            model_name='car_list',
            name='brand',
            field=models.CharField(default='', max_length=30, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='car_list',
            name='engine',
            field=models.CharField(default='', max_length=30, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='car_list',
            name='model',
            field=models.CharField(default='', max_length=30, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car_list',
            name='price_byn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (BYN)'),
        ),
        migrations.AddField(
            model_name='car_list',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (USD)'),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car_list',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
